# Generated by Django 4.0.3 on 2022-03-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='human_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='human_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='human_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм'),
        ),
    ]
